apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mongodb0
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mongo-0 
  template: 
    metadata: 
      labels: 
        app: mongo-0 
    spec: 
      terminationGracePeriodSeconds: 10 
      containers: 
        - name: mongo 
          image: mongo:4.2.23-bionic
          resources:
            requests:
              memory: "3072Mi"
              cpu: "1500m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          name: mongo
          args: ["--dbpath","/data/db"]
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
            - name: MONGODB_ROLE 
              value: root 
            - name: REPLICA_ID 
              value: mongoRS 
            - name: HOST 
              value: mongodb0 
          ports: 
            - containerPort: 27017 
          volumeMounts: 
            - name: mongo-key 
              mountPath: "/etc/secrets-volume" 
              readOnly: true 
            - name: mongo-persistent-storage 
              mountPath: /data 
      volumes: 
      - name: mongo-key 
        secret: 
          defaultMode: 0400 
          secretName: mongo-key 
      - name: mongo-persistent-storage 
        persistentVolumeClaim: 
          claimName: mongo-0-disk 
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mongodb1 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mongo-1 
  template: 
    metadata: 
      labels: 
        app: mongo-1 
    spec: 
      terminationGracePeriodSeconds: 10 
      containers: 
        - name: mongo 
          image: mongo:4.2.23-bionic
          resources:
            requests:
              memory: "3072Mi"
              cpu: "1500m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          name: mongo
          args: ["--dbpath","/data/db"]
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
            - name: MONGODB_ROLE 
              value: root 
            - name: REPLICA_ID 
              value: mongoRS 
            - name: HOST 
              value: mongodb0 
          ports: 
            - containerPort: 27017 
          volumeMounts: 
            - name: mongo-key 
              mountPath: "/etc/secrets-volume" 
              readOnly: true 
            - name: mongo-persistent-storage 
              mountPath: /data 
      volumes: 
      - name: mongo-key 
        secret: 
          defaultMode: 0400 
          secretName: mongo-key 
      - name: mongo-persistent-storage 
        persistentVolumeClaim: 
          claimName: mongo-1-disk 
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mongodb2 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mongo-2 
  template: 
    metadata: 
      labels: 
        app: mongo-2 
    spec: 
      terminationGracePeriodSeconds: 10 
      containers: 
        - name: mongo 
          image: mongo:4.2.23-bionic
          resources:
            requests:
              memory: "3072Mi"
              cpu: "1500m"
            limits:
              memory: "4096Mi"
              cpu: "2000m"
          name: mongo
          args: ["--dbpath","/data/db"]
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
            - name: MONGODB_ROLE 
              value: root 
            - name: REPLICA_ID 
              value: mongoRS 
            - name: HOST 
              value: mongodb0 
          ports: 
            - containerPort: 27017 
          volumeMounts: 
            - name: mongo-key 
              mountPath: "/etc/secrets-volume" 
              readOnly: true 
            - name: mongo-persistent-storage 
              mountPath: /data 
      volumes: 
      - name: mongo-key 
        secret: 
          defaultMode: 0400 
          secretName: mongo-key 
      - name: mongo-persistent-storage 
        persistentVolumeClaim: 
          claimName: mongo-2-disk 
