services:
  random:
    build:
      context: random
    ports:
      - "8090:8090"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  reaper:
    build:
      context: reaper
