services:
  nginx:
    depends_on:
      webapp:
        condition: service_started
      exchange:
        condition: service_started
      random:
        condition: service_started
    image: nginx:1.16.0-alpine
    volumes:
      - ../infra/nginx/localhost/nginx.conf:/etc/nginx/nginx.conf
      - ../infra/nginx/localhost/localhost.crt:/etc/nginx/localhost.crt
      - ../infra/nginx/localhost/localhost.key:/etc/nginx/localhost.key
    ports:
      - "80:80"
      - "443:443"

  random:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: random
    environment:
      MongoURI: mongodb://mongo:27017/
      MongoUser: adminuser
      MongoPass: password123
      LogLevel: Debug

  webapp:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: webapp
    environment:
      ENV: local
      SessionKey: efnic74mh5Ki1EWHoZFNgEnZJ3IZKsLu
      CaptchaKey: ${CaptchaKey}
      MongoURI: mongodb://mongo:27017/
      MongoUser: adminuser
      MongoPass: password123
      LogLevel: Debug
      EmailUser: ${EmailUser}
      EmailPass: ${EmailPass}
        
  exchange:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: exchange
    environment:
      MongoURI: mongodb://mongo:27017/
      MongoUser: adminuser
      MongoPass: password123
      LogLevel: Debug

  reaper:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: reaper
    environment:
      MongoURI: mongodb://mongo:27017/
      MongoUser: adminuser
      MongoPass: password123
      WriteThreshold: 10
      LogLevel: Debug

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=adminuser
        - MONGO_INITDB_ROOT_PASSWORD=password123

