services:
  nginx:
    depends_on:
      ew-webapp:
        condition: service_started
      ew-exchange:
        condition: service_started
      ew-random:
        condition: service_started
    image: nginx:1.25-alpine
    volumes:
      - ../infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../infra/nginx/localhost/localhost.crt:/etc/nginx/tls.crt
      - ../infra/nginx/localhost/localhost.key:/etc/nginx/tls.key
    ports:
      - "80:80"
      - "443:443"

  ew-random:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: random
    environment:
      MongoURI: mongodb://mongo:27017/
      MongoUser: adminuser
      MongoPass: password123
      LogLevel: Debug

  ew-webapp:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: webapp
    environment:
      ENV: local
      SessionKey: efnic74mh5Ki1EWHoZFNgEnZJ3IZKsLu
      CaptchaKey: ${CaptchaKey}
      MongoURI: mongodb://mongo:27017/
      MongoUser: adminuser
      MongoPass: password123
      LogLevel: Debug
      EmailUser: ${EmailUser}
      EmailPass: ${EmailPass}
        
  ew-exchange:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: exchange
    environment:
      MongoURI: mongodb://mongo:27017/
      MongoUser: adminuser
      MongoPass: password123
      LogLevel: Debug

  ew-reaper:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: reaper
    environment:
      MongoURI: mongodb://mongo:27017/
      MongoUser: adminuser
      MongoPass: password123
      WriteThreshold: 10
      LogLevel: Debug

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=adminuser
        - MONGO_INITDB_ROOT_PASSWORD=password123
