services:
  random:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: random
    ports:
      - "8090:8090"
    environment:
      MongoURI: mongodb://mongo:27017
      MongoUser: adminuser
      MongoPass: password123
      LogLevel: Debug
        
  exchange:
    build:
      context: exchange
    ports:
      - "8081:8081"
    environment:
      MongoURI: mongodb://mongo:27017
      MongoUser: adminuser
      MongoPass: password123
      LogLevel: Info

  reaper:
    depends_on:
      mongo:
        condition: service_started
    build:
      context: reaper
    environment:
      MongoURI: mongodb://mongo:27017
      MongoUser: adminuser
      MongoPass: password123
      LogLevel: Debug

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
        # provide your credentials here
        - MONGO_INITDB_ROOT_USERNAME=adminuser
        - MONGO_INITDB_ROOT_PASSWORD=password123

