apiVersion: apps/v1
kind: Deployment
metadata:
  name: ew-random
  labels:
    name: ew-random
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ew-random
  template:
    metadata:
      labels:
        name: ew-random
    spec:
      imagePullSecrets:
        - name: ghcrcred
      serviceAccountName: ew-random
      containers:
        - name: ew-random
          securityContext:
            privileged: true
          image: "ghcr.io/ktraister/ew_random:1447f56f9d6f8abcc34b510369b2ea8202982b29"
          imagePullPolicy: Always
          env:
            - name: "MongoURI"
              valueFrom:
                secretKeyRef:
                  key:  mongouri
                  name: ew-reaper
            - name: "MongoUser"
              valueFrom:
                secretKeyRef:
                  key:  mongouser
                  name: ew-reaper
            - name: "MongoPass"
              valueFrom:
                secretKeyRef:
                  key:  mongopass
                  name: ew-reaper
          ports:
            - containerPort: 8090
