apiVersion: apps/v1
kind: Deployment
metadata:
  name: ew-random
  labels:
    name: ew-random
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ew-random
  template:
    metadata:
      labels:
        name: ew-random
    spec:
      imagePullSecrets:
        - name: ghcrcred
      serviceAccountName: ew-random
      containers:
        - name: ew-random
          securityContext:
            privileged: true
          image: "ghcr.io/ktraister/ew_random:5866f78189f6cad6f88eab18651176d117cef6f2"
          imagePullPolicy: Always
          env:
            - name: "MongoURI"
              valueFrom:
                secretKeyRef:
                  key:  MongoURI
                  name: ew-config
            - name: "MongoUser"
              valueFrom:
                secretKeyRef:
                  key:  username
                  name: mongo-creds
            - name: "MongoPass"
              valueFrom:
                secretKeyRef:
                  key:  password
                  name: mongo-creds
          ports:
            - containerPort: 8090
