apiVersion: apps/v1
kind: Deployment
metadata:
  name: ew-random
  labels:
    name: ew-random
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ew-random
  template:
    metadata:
      labels:
        name: ew-random
    spec:
      imagePullSecrets:
        - name: ghcrcred
      serviceAccountName: ew-random
      containers:
        - name: ew-random
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "128Mi"
              cpu: "128m"
          securityContext:
            privileged: true
          image: "ghcr.io/ktraister/ew_random:GITHUB_SHA"
          imagePullPolicy: Always
          env:
            - name: "MongoURI"
              valueFrom:
                secretKeyRef:
                  key:  MongoURI
                  name: ew-config
            - name: "MongoUser"
              valueFrom:
                secretKeyRef:
                  key:  username
                  name: mongo-creds
            - name: "MongoPass"
              valueFrom:
                secretKeyRef:
                  key:  password
                  name: mongo-creds
            - name: "ClientVersion"
              valueFrom:
                secretKeyRef:
                  key:  ClientVersion
                  name: ew-config
            - name: "CoinbaseAPIKey"
              valueFrom:
                secretKeyRef:
                  key:  CoinbaseAPIKey
                  name: ew-config
            - name: "StripeAPIKey"
              valueFrom:
                secretKeyRef:
                  key:  StripeAPIKey
                  name: ew-config
          ports:
            - containerPort: 8090
