apiVersion: v1
kind: Service
metadata:
  name: ew-random
  labels:
    app: ew-random
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: ew-random
