version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/endless_waltz"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/endless_waltz/random"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/endless_waltz/exchange"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/endless_waltz/webapp"
    schedule:
      interval: "weekly"
