apiVersion: apps/v1
kind: Deployment
metadata:
  name: ew-reaper
  labels:
    name: ew-reaper
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ew-reaper
  template:
    metadata:
      labels:
        name: ew-reaper
    spec:
      imagePullSecrets:
        - name: ghcrcred
      serviceAccountName: ew-reaper
      containers:
        - name: ew-reaper
          securityContext:
            privileged: true
          image: "ghcr.io/ktraister/ew_reaper:1444ca8b070c38f7a77c9f3ae7d950f3a71502a7"
          imagePullPolicy: Always
          env:
            - name: "MongoURI"
              valueFrom:
                secretKeyRef:
                  key:  MongoURI
                  name: ew-reaper
            - name: "MongoUser"
              valueFrom:
                secretKeyRef:
                  key:  MongoUser
                  name: ew-reaper
            - name: "MongoPass"
              valueFrom:
                secretKeyRef:
                  key:  MongoPass
                  name: ew-reaper
            - name: "WriteThreshold"
              value: "1000"
        - name: ew-entropy
          securityContext:
            privileged: true
          image: "ghcr.io/ktraister/ew_entropy:34b1d65b6662529f53a81ea081c8d6794824f663"
          imagePullPolicy: Always
          env:
            - name: "RTLDevIndex"
              value: "1" 
          volumeMounts: 
          - mountPath: "/tmp"
            name: bridge
          - mountPath: "/dev/bus/usb/001/003"
            name: radio-mount
      volumes:
      - name: radio-mount
        hostPath: 
          path: "/dev/bus/usb/001/003"
      - name: bridge

