apiVersion: v1
kind: Service
metadata:
  name: ew-proxy
  labels:
    app: ew-proxy
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: socks
  selector:
    name: ew-proxy
