apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
data:
  mongouri: {{ .Values.mongouri | b64enc }}
  mongopass: {{ .Values.mongopass | b64enc }}
  mongouser: {{ .Values.mongouser | b64enc }}
