server:
  key: "./certs/server.key"
  cert: "./certs/server.crt"
  randomURL: "http://localhost:8090/api/otp"
  exchangeURL: "http://localhost:8081/api/otp"
  logLevel: "Fatal"
  API_Key: "arandomnumber"
