apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      serviceAccountName: nginx
      containers:
        - name: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "128Mi"
              cpu: "128m"
          securityContext:
            privileged: true
          image: "nginx:1.25-alpine"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 8080
          volumeMounts:
          - name: config 
            mountPath: "/etc/nginx"
            readOnly: true
      volumes:
      - name: config
        secret:
          secretName: nginx-config
