#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: nginx-hpa
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment  # Adjust the kind based on your workload type (Deployment, StatefulSet, etc.)
#    name: nginx
#  minReplicas: 3
#  maxReplicas: 10  # Adjust the maximum number of replicas as needed
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 75
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: Utilization
#        averageUtilization: 75
