apiVersion: apps/v1
kind: Deployment
metadata:
  name: ew-exchange
  labels:
    name: ew-exchange
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ew-exchange
  template:
    metadata:
      labels:
        name: ew-exchange
    spec:
      imagePullSecrets:
        - name: ghcrcred
      serviceAccountName: ew-exchange
      containers:
        - name: ew-exchange
          securityContext:
            privileged: true
          image: "ghcr.io/ktraister/ew_exchange:GITHUB_SHA"
          imagePullPolicy: Always
          env:
            - name: "MongoURI"
              valueFrom:
                secretKeyRef:
                  key:  MongoURI
                  name: ew-config
            - name: "MongoUser"
              valueFrom:
                secretKeyRef:
                  key:  username
                  name: mongo-creds
            - name: "MongoPass"
              valueFrom:
                secretKeyRef:
                  key:  password
                  name: mongo-creds
          ports:
            - containerPort: 8081
