apiVersion: v1
kind: Service
metadata:
  name: ew-exchange
  labels:
    app: ew-exchange
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    name: ew-exchange
