apiVersion: v1
kind: Pod
metadata:
  name: mongoclient
  labels:
    app: mongoclient
spec:
  containers:
  - image: mongoclient/mongoclient
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: mongoclient
  restartPolicy: Always
