apiVersion: apps/v1
kind: Deployment
metadata:
  name: ew-webapp
  labels:
    name: ew-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ew-webapp
  template:
    metadata:
      labels:
        name: ew-webapp
    spec:
      imagePullSecrets:
        - name: ghcrcred
      serviceAccountName: ew-webapp
      containers:
        - name: ew-webapp
          securityContext:
            privileged: true
          image: "ghcr.io/ktraister/ew_webapp:c82703c460b4b5a41d96db9622e2c315a7cde713"
          imagePullPolicy: Always
          env:
            - name: "SessionKey"
              valueFrom:
                secretKeyRef:
                  key: SessionKey
                  name: ew-config
            - name: "CaptchaKey"
              valueFrom:
                secretKeyRef:
                  key: CaptchaKey
                  name: ew-config
            - name: "EmailUser"
              valueFrom:
                secretKeyRef:
                  key: EmailUser
                  name: ew-config
            - name: "EmailPass"
              valueFrom:
                secretKeyRef:
                  key: EmailPass
                  name: ew-config
            - name: "MongoURI"
              valueFrom:
                secretKeyRef:
                  key:  MongoURI
                  name: ew-config
            - name: "MongoUser"
              valueFrom:
                secretKeyRef:
                  key:  username
                  name: mongo-creds
            - name: "MongoPass"
              valueFrom:
                secretKeyRef:
                  key:  password
                  name: mongo-creds
          ports:
            - containerPort: 8080
