apiVersion: v1
kind: Service
metadata:
  name: ew-webapp
  labels:
    app: ew-webapp
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: ew-webapp
