on:
  push:
    paths:
      - endless_waltz/reaper/**
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./endless_waltz/reaper
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ew_reaper:${{ github.sha }}
