on:
  push:
    paths:
      - endless_waltz/reaper/**
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push docker image
        run: | 
          ls
          cd ./endless_waltz/reaper
          docker build . -t "ghcr.io/ktraister/ew-reaper:$GITHUB_SHA"
          docker push "ghcr.io/ktraister/ew-reaper:$GITHUB_SHA"

