on:
  push:
    paths:
      - endless_waltz/exchange/**
      - infra/k8s/exchange/**
      #    branches:
      #      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd endless_waltz/exchange
          go build -tags netgo -a -v .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: endless_waltz/exchange
          file: endless_waltz/exchange/Dockerfile
          push: true
          tags: "ghcr.io/ktraister/ew_exchange:${{ github.sha }}"

      - name: Deploy Setup
        run: | 
          sed -i "s/GITHUB_SHA/${{ github.sha }}/" infra/k8s/exchange/deployment.yaml

      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f infra/k8s/exchange
