on:
  pull_request:
    types: [ opened, synchronize ]

env:
  GOPRIVATE: "github.com/ktraister"
jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/client
          go test
          go build -tags netgo -a -v .

  random:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/random
          go test
          go build -tags netgo -a -v .

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: false

  reaper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/reaper
          go test
          go build -tags netgo -a -v .

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: false

  server:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Test
        run: | 
          go test

      - name: Go Build
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/server
          go test
          go build -tags netgo -a -v .

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: false

  common:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Test
        run: | 
          cd ./endless_waltz/common
          go test
