on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/cli
          go test -v
          go build -tags netgo -a -v .

  gui:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/gui
          go install fyne.io/fyne/v2/cmd/fyne@latest
          go test -v
          go build -tags netgo -a -v .

  common:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/common
          go test -v

  random:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/random
          go test -v
          go build -tags netgo -a -v .

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: ./endless_waltz/random
          file: ./endless_waltz/random/Dockerfile
          push: false

  exchange:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/exchange
          go test -v
          go build -tags netgo -a -v .

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: ./endless_waltz/exchange
          file: ./endless_waltz/exchange/Dockerfile
          push: false


  reaper:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build and Test
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd ./endless_waltz/reaper
          go test -v 
          go build -tags netgo -a -v .

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: ./endless_waltz/reaper
          file: ./endless_waltz/reaper/Dockerfile
          push: false
