on:
  push:
    paths:
      - endless_waltz/proxy/**
      - infra/k8s/proxy/**
    branches:
      - "main"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd endless_waltz/proxy
          go build -tags netgo -a -v .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: endless_waltz/proxy
          file: endless_waltz/proxy/Dockerfile
          push: true
          tags: "ghcr.io/ktraister/ew_proxy:${{ github.sha }}"

      - name: Deploy 
        run: | 
          sed -i "s/GITHUB_SHA/${{ github.sha }}/" infra/k8s/proxy/deployment.yaml
          echo "${{ secrets.SHENLONG_KUBECONFIG }}" > ./config.yaml
          export KUBECONFIG=./config.yaml
          kubectl apply -f infra/k8s/proxy
