on:
  push:
    paths:
      - endless_waltz/webapp/**
      - endless_waltz/common/**
      - infra/k8s/webapp/**
    branches:
      - "main"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3

      - name: Go Build
        run: | 
          export GOOS=linux
          export GOARCH=amd64
          export CGO_ENABLED=0
          cd endless_waltz/webapp
          go build -tags netgo -a -v .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: endless_waltz/webapp
          file: endless_waltz/webapp/Dockerfile
          push: true
          tags: "ghcr.io/ktraister/ew_webapp:${{ github.sha }}"

      - name: Deploy 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AUTOMATION_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AUTOMATION_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
        run: | 
          myIp=`curl icanhazip.com`
 
          aws ec2 authorize-security-group-ingress \
              --group-id sg-0b4d4b8d9f3867832 \
              --protocol tcp \
              --port 6443 \
              --cidr "$myIp/32"

          sed -i "s/GITHUB_SHA/${{ github.sha }}/" infra/k8s/webapp/deployment.yaml
          echo "${{ secrets.ULTRON_KUBECONFIG }}" > ./config.yaml
          export KUBECONFIG=./config.yaml
          kubectl apply -f infra/k8s/webapp
          rm -rfv ./config.yaml                                                                                                                                          
 
          aws ec2 revoke-security-group-ingress \
              --group-id sg-0b4d4b8d9f3867832 \
              --protocol tcp \
              --port 6443 \
              --cidr "$myIp/32"
